#!/usr/bin/env ruby
require 'bundler'

Bundler.require
Dir["lib/*.rb"].map { |f| require_relative f }

class Advent < Thor
  desc "day DAY PART", "run the thing for a day"
  def day(day_num, part_num)
    problem = Kernel.const_get("Day#{day_num}::Part#{part_num}")
    puts problem.new.run
  end

  desc "create DAY", "create files for day from template"
  def create(day_num)
    files = Dir["**/*.template"]
    files.each do |file|
      template = File.read(file)
      output = template.gsub("N", day_num)
      outfile = file.gsub("N", day_num).gsub(".template", "")
      File.open(outfile, "w") do |out|
        out.puts output
      end
    end
  end
end

Advent.start
